# Generated by Django 5.2.7 on 2025-10-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('kitchen', 'Kitchen Staff'), ('DELIVERY', 'Delivery Partner')], default='CUSTOMER', max_length=20),
        ),
    ]
