# Generated by Django 5.2.7 on 2025-10-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin'), ('kITCHEN', 'Kitchen Staff'), ('DELIVERY', 'Delivery Partner')], default='CUSTOMER', max_length=20),
        ),
    ]
